modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/JAOPCAGT/issues"

[[mods]]
	modId = "jaopcagtceu"
	version = "0@VERSION@"
	displayName = "JAOPCAGTCEu"
	description = "An addon to JAOPCA that adds GregTechCEu Modern support."
	logoFile = "jaopcagt.logo.png"
	credits = "Inspired by AOBD, a mod by ganymedes01"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/jaopcagt"

[[dependencies.jaopca]]
	modId = "forge"
	versionRange = "[41.0.94,)"
	mandatory = true

[[dependencies.jaopcagtceu]]
	modId = "jaopca"
	versionRange = "[4.2,)"
	mandatory = true

[[dependencies.jaopcagtceu]]
	modId = "gtceu"
	versionRange = "[1.1,)"
	mandatory = true
